/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TextFileSearch;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author RlzRolland
 */
public class TextFileSearch extends javax.swing.JFrame {

    ImageIcon menos = new ImageIcon(getClass().getResource("negativo.png"));
    ImageIcon mas = new ImageIcon(getClass().getResource("mas.png"));
    Icon iconito = new ImageIcon(getClass().getResource("mensaje.png"));
    int valor = 0;
    String[] opciones = {"Si / Yes", "No"};

    /**
     * Creates new form MyNigga
     */
    public TextFileSearch() {
        initComponents();
        this.setTitle("TextFileSearch");
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("database-search.png")).getImage());
        jTabbedPane1.insertTab("", mas, null, "Agregar Pestaña / Add Tab", 0);
        jTabbedPane1.insertTab("", menos, null, "Eliminar Pestaña / Remove Tab", 1);
        jTabbedPane1.insertTab("Base de datos / Database 1", null, new BD(), "Base de datos / Database 1", 2);
        jTabbedPane1.setSelectedIndex(2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTabbedPane1MousePressed(evt);
            }
        });

        jMenu2.setText("Acerca de... / About...");

        jMenuItem3.setText("Información del Programa");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Program Information");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Creditos / Credits");

        jMenuItem7.setText("Creditos / Credits");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1010, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MousePressed
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex() == 0) {
            int i = JOptionPane.showOptionDialog(null, "¿Quieres abrir una nueva pestaña? / Do you want to open a new tab?",
                    "Abrir Pestaña / Open Tab",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, iconito, opciones, opciones[0]);
            if (i == 0) {
                int tab = jTabbedPane1.getTabCount();
                jTabbedPane1.insertTab("Base de datos / Database " + (tab - 1), null, new BD(), "Base de datos / Database ", tab);
                jTabbedPane1.setSelectedIndex(tab);
            }
            if (i == 1) {
                JOptionPane.showMessageDialog(null, "La pestaña no fue abierta / The tab was not opened");
            }
        }

        if (jTabbedPane1.getSelectedIndex()
                == 1) {
            int j = JOptionPane.showOptionDialog(null, "¿Quieres cerrar esta pestaña? / Do you want to close this tab?",
                    "Abrir Pestaña / Open Tab",
                    JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, iconito, opciones, opciones[0]);
            if (j == 0) {
                if (valor == 0) {
                } else {
                    if (jTabbedPane1.getTabCount() > 3 && jTabbedPane1.getSelectedIndex() != 0) {
                        jTabbedPane1.remove(valor);
                        jTabbedPane1.setSelectedIndex(2);
                        valor = 0;
                        for (int m = 2; m < jTabbedPane1.getTabCount(); m++) {
                            jTabbedPane1.setTitleAt(m, "Base de datos / Database " + (m - 1));
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Debe existir al menos una BD abierta / There must be at least one open DB");
                        jTabbedPane1.setSelectedIndex(2);
                    }
                }
            }
        } else {
            valor = jTabbedPane1.getSelectedIndex();
        }
    }//GEN-LAST:event_jTabbedPane1MousePressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "TextFileSearch es un programa que realiza búsquedas en archivos de texto (BD). "
                + "\nEl único requerimiento para "
                + "\ncargar una base de datos es que esta última esté delimitada por tabuladores. Para realizar las búsquedas "
                + "\nel usuario cuenta con 2 opciones; La primera es realizando una búsqueda general en todo el archivo y la "
                + "\nsegunda especificando en que columna se desea buscar; a su vez es posible eliminar ciertas columnas "
                + "\ndel archivo en curso y en su caso volver a generar las columnas que hayan sido previamente eliminadas."
                + "\nFinalmente, TextFileSearch puede cargar diferentes bases de datos de manera simultánea y exportar las "
                + "\nbúsquedas en forma de texto. "
                + "\n\nPara mayor información referirse al manual de usuario. ", "TextFileSearch", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "TextFileSearch is a software that searches in text files (DB)."
                + "\nThe only requirement to load a database is that "
                + "\nthe latter has to be delimited by tabs. To perform the searches, the user has 2 options. The first one is "
                + "\ndoing a general search in the whole file and the second specifying in which column you want to search, "
                + "\nin turn it is possible to eliminate certain columns of the current file and, if necessary, re-generate the  "
                + "\ncolumns that have been previously deleted. Finally, TextFileSearch can load different databases"
                + "\nsimultaneously and export the searches in text. "
                + "\n\nFor more information refer to the user manual. ", "TextFileSearch", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Programa realizado por José Eduardo Rolland Geraldo "
                + "\n"
                + "\nProgram Realized by José Eduardo Rolland Geraldo ");
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Napkin".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextFileSearch.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextFileSearch.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextFileSearch.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextFileSearch.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        try {
            //here you can put the selected theme class name in JTattoo
            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
 
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextFileSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextFileSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextFileSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextFileSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TextFileSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem7;
    public javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
